# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('selectorType', models.IntegerField()),
                ('selectorValue', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=999999)),
                ('testCaseId', models.BigIntegerField()),
                ('runOrder', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('hasInput', models.CharField(max_length=1)),
                ('hasElement', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='actionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ActionType'),
        ),
    ]
