# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('selectorValue', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=999999)),
                ('runOrder', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('hasInput', models.CharField(max_length=1)),
                ('hasElement', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('selectorValue', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=999999)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Action')),
            ],
        ),
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SelectorType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
                ('runOrder', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='outputType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.OutputType'),
        ),
        migrations.AddField(
            model_name='output',
            name='selectorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.SelectorType'),
        ),
        migrations.AddField(
            model_name='action',
            name='actionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='selectorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.SelectorType'),
        ),
        migrations.AddField(
            model_name='action',
            name='testCaseStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TestCaseStep'),
        ),
    ]
