# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='testCaseId',
            new_name='testCaseStepId',
        ),
    ]
